### ISSUE TITLE
Verify the uniqueness of records by key

### ISSUE THREAD

**Issue by cpiraux** [pharmaverse/metatools#52]
It could be interesting to add function to check that the key uniquely identifies each record in the dataset
Reference:
o	Define-XML Version 2.0 Completion Guidelines pg 11
![image](https://user-images.githubusercontent.com/69685640/234189955-f8d65f30-9605-434d-8b9b-7ce32e26926a.png)

o	ADaM v2.1 pg 14
![image](https://user-images.githubusercontent.com/69685640/234190003-500c6013-9a52-4430-9c6d-de7f5ad902c4.png)

**Comment by EeethB** [comment]
@statasaurus we were discussing a similar feature requested in {xportr}, but I think it makes more sense here. Is this something that is being worked on, or would you be interested in a PR for it?

**Comment by statasaurus** [comment]
I am planning on doing a bit of a sprint on metacore over the next week or two to get somethings sorted through. But if you would like to do a PR that would be great. I agree this makes sense to have, but I think it fits better within meta tools rather than metacore. Cause metacore doesn't check things against the datasets it only gets against the metadata
